// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp2xxz8TonxgD1N0bpf5pGXEbcF8_ubFU',
    appId: '1:535188923299:web:a1640853f2edd55958b016',
    messagingSenderId: '535188923299',
    projectId: 'tranz-house',
    authDomain: 'tranz-house.firebaseapp.com',
    storageBucket: 'tranz-house.appspot.com',
    measurementId: 'G-8NFWLF9JL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn39uxV5XRtt2JoHzijzzmw57A2Nk4emI',
    appId: '1:535188923299:android:cfe9e45ab302d65858b016',
    messagingSenderId: '535188923299',
    projectId: 'tranz-house',
    storageBucket: 'tranz-house.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_A6Ic0MtI-tW8YYdbX3Rd0avSGVvZ_ZY',
    appId: '1:535188923299:ios:7483669f9d75fb2358b016',
    messagingSenderId: '535188923299',
    projectId: 'tranz-house',
    storageBucket: 'tranz-house.appspot.com',
    androidClientId: '535188923299-dcc4iu1c9jsj2psn3ji8qbh4bjfpan9p.apps.googleusercontent.com',
    iosClientId: '535188923299-ki6ntp5tchgag43dff828vp6n0nj6inn.apps.googleusercontent.com',
    iosBundleId: 'com.tranzhouse.app',
  );
}
